version: '3.7'

services:
  client:
    build: .
    container_name: jscangaceiro-client
    volumes:
      - .:/home/jscangaceiro/client
    ports:
      - "8080:8080"
    environment: 
      - NODE_ENV=development